[package]
name = "pixely"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.13.0"
raw-window-handle = "0.5.0"
wgpu = "0.15.0"
